name: Today in Science CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js version 14 and 16
        uses: actions/setup-node@v3
        with:
          node-version: [14.x, 16.x]
      - run: npm install server
      - run: npm test
